name: GitHub Actions

on: push

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-2019, ubuntu-18.04]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 13

            - name: Installation Phase
              run: yarn install --frozen-lockfile

            - name: Packaging, Linting and Testing Phase
              run: |
                  yarn client lint
                  yarn client tsc
                  yarn client test
                  yarn server test
